### ISSUE TITLE
Can you change the Icon...

### ISSUE THREAD

**Issue by ghollingworth** [chipcode-nl/picoprobe-mac#3]
Hi,

Can you please change the icon for this, you are using the trademarked Raspberry Pi icon when you shouldn't (it can only be used by us or under some special circumstances where our products are being sold)

Thanks

Gordon Hollingworth
Raspberry Pi CTO (Software)

**Comment by chipcode-nl** [comment]
It is not a product it is only a tutorial how to use the Pico probe.

**Comment by ghollingworth** [comment]
That makes no difference and does not mean you are allowed to violate our trademarks.

**Comment by chipcode-nl** [comment]
I consider this fair use, it is used for educational or information purposes. I made it so other users can easily use the pico probe. I made it with the best intend. I am sorry that after all these years this is suddenly a problem.

**Comment by ghollingworth** [comment]
The trademark rules are quite clear:

https://www.raspberrypi.com/trademark-rules/

![image](https://github.com/chipcode-nl/picoprobe-mac/assets/2048540/1f448d21-0a6a-43f7-8372-05fb86ed1e89)

Just make up an icon of your own for your work.

**Comment by chipcode-nl** [comment]
Gordon,

I am a little confused, why would you worry about a free opensource tool that I made on the launch of the RP2040 chip because there was no support for the Mac at this time. It is only downloaded 4,728 times, it is a waste of your time, unless it has something to do with the announced Initial Public Offering. I can remove the public repro if it makes you happy. 

That being said, you can hire me, I am still passionate about embedded systems, robotics, machine learning, wrote a full multicore OS for the RP2040, was parttime lecturer at Amsterdam University of Applied Sciences where I made the embedded system course the highest rated course of the whole University (according the Students). 

So if your are interested you can send me a message.

Best regards,
Carl van Heezik

**Comment by ghollingworth** [comment]
No, it has nothing to do with a possible IPO, it's completely normal to check for people using your trademarks without your permission.  In general, when it's a company we just get a lawyer to write them a cease and desist letter (this is also done by every other company in the world if they care in any way about their trademarks).  If you don't do that, then other people can use it as a counter-example, "I don't see why I can't call it a Hoover, everyone calls it a Hoover even though it's made by Electrolux"

I saw this when I searched the VSCode extension for "Raspberry":

![image](https://github.com/chipcode-nl/picoprobe-mac/assets/2048540/fc541e7c-d95c-47b4-b2af-78376bbb6a72)

This isn't fair use, it is more like "passing-off".  A third party, may think this is an official Raspberry Pi extension and is supported and published by Raspberry Pi because it uses our logo.  That's the whole point of having a logo, it represents your brand and values and communicates that to your users.

I'm not asking you to take down the extension, we're super happy for you to support things like this but please, just update it to change the logo to something that represents your own software.

P.S. Note you are using the PICOPROBE trademark which is not owned by Raspberry Pi, we've recently been asked to change our use of picoprobe to debugprobe because it was a trademark owned by a third party.  So you're not the only one who gets asked to change things like this.

**Comment by chipcode-nl** [comment]
Replaced the icon.

**Comment by ghollingworth** [comment]
Thankyou
